server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userServiceLibraryManagement?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MYSQL80Dialect
  application:
    name: UserAuthenticationService

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: todotracker80@gmail.com
#    password: tqzrfbigyhysnpeq
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

